// <auto-generated />
using System;
using CommunityElderCare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityElderCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunityCareDbContext))]
    [Migration("20260824103041_AddIdentityAndConsent")]
    partial class AddIdentityAndConsent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ElderProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttentionLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoDisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("NextCheckInDueAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AttentionLevel");

                    b.ToTable("ElderProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ElderProfiles_IsDemoData", "\"IsDemoData\" = 1");
                        });
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DemoName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "ContactOrder")
                        .IsUnique();

                    b.ToTable("EmergencyContacts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.HealthRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "Code")
                        .IsUnique();

                    b.ToTable("HealthRisks", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ServiceNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "Code")
                        .IsUnique();

                    b.ToTable("ServiceNeeds", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.AccessAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldList")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "OccurredAt");

                    b.ToTable("AccessAuditRecords", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.BreakGlassGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommunityStaffUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "CommunityStaffUserId", "CareEventId", "ExpiresAt");

                    b.ToTable("BreakGlassGrants", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GranteeUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "GranteeUserId", "ExpiresAt");

                    b.ToTable("ConsentGrants", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrantField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsentGrantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsentGrantId", "Field")
                        .IsUnique();

                    b.ToTable("ConsentGrantFields", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.EmergencyContact", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.HealthRisk", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("HealthRisks")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ServiceNeed", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("ServiceNeeds")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrantField", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Identity.ConsentGrant", null)
                        .WithMany("Fields")
                        .HasForeignKey("ConsentGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ElderProfile", b =>
                {
                    b.Navigation("EmergencyContacts");

                    b.Navigation("HealthRisks");

                    b.Navigation("ServiceNeeds");
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrant", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
