// <auto-generated />
using System;
using CommunityElderCare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityElderCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunityCareDbContext))]
    [Migration("20260824132922_AddAiDraftsAndMemory")]
    partial class AddAiDraftsAndMemory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CommunityElderCare.Core.Ai.AiDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "Status", "CreatedAt");

                    b.ToTable("AiDrafts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Ai.MemoryCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "ConfirmedAt");

                    b.ToTable("MemoryCandidates", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.CareEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentOwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIncompleteMandatoryTask")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFollowUpCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresFollowUp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilityQueue")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "SourceEventId")
                        .IsUnique();

                    b.HasIndex("ElderId", "Status");

                    b.ToTable("CareEvents", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.CareEventEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareEventId", "RecordedAt");

                    b.HasIndex("CareEventId", "SourceEventId")
                        .IsUnique();

                    b.ToTable("CareEventEvidence", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.CareEventTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareEventId", "OccurredAt");

                    b.ToTable("CareEventTransitions", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.ContactAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeterministicAttemptId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareEventId", "DeterministicAttemptId")
                        .IsUnique();

                    b.ToTable("ContactAttempts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareWork.FollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedStaffUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffUserId", "DueAt");

                    b.HasIndex("CareEventId", "Status");

                    b.ToTable("FollowUps", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareWork.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedWorkerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInstruction")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledWindow")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedWorkerUserId", "Status");

                    b.HasIndex("CareEventId", "Status");

                    b.ToTable("ServiceOrders", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareWork.VisitTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedStaffUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmedSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawStaffNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledEndAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledStartAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffUserId", "ScheduledStartAt");

                    b.HasIndex("CareEventId", "Status");

                    b.ToTable("VisitTasks", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CheckIns.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ClientTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "ReceivedAt");

                    b.HasIndex("ElderId", "RequestId", "Kind")
                        .IsUnique();

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CheckIns.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "RequestId", "Kind")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.CheckIns.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SnoozedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnoozedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "NextDueAt");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ElderProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttentionLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoDisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("NextCheckInDueAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AttentionLevel");

                    b.ToTable("ElderProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ElderProfiles_IsDemoData", "\"IsDemoData\" = 1");
                        });
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DemoName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "ContactOrder")
                        .IsUnique();

                    b.ToTable("EmergencyContacts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.HealthRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "Code")
                        .IsUnique();

                    b.ToTable("HealthRisks", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ServiceNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "Code")
                        .IsUnique();

                    b.ToTable("ServiceNeeds", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.AccessAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldList")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "OccurredAt");

                    b.ToTable("AccessAuditRecords", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.BreakGlassGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommunityStaffUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "CommunityStaffUserId", "CareEventId", "ExpiresAt");

                    b.ToTable("BreakGlassGrants", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GranteeUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderId", "GranteeUserId", "ExpiresAt");

                    b.ToTable("ConsentGrants", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrantField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsentGrantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsentGrantId", "Field")
                        .IsUnique();

                    b.ToTable("ConsentGrantFields", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ElderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Ai.AiDraft", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Ai.MemoryCandidate", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.CareEventEvidence", b =>
                {
                    b.HasOne("CommunityElderCare.Core.CareEvents.CareEvent", null)
                        .WithMany("Evidence")
                        .HasForeignKey("CareEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.CareEventTransition", b =>
                {
                    b.HasOne("CommunityElderCare.Core.CareEvents.CareEvent", null)
                        .WithMany("Transitions")
                        .HasForeignKey("CareEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.ContactAttempt", b =>
                {
                    b.HasOne("CommunityElderCare.Core.CareEvents.CareEvent", null)
                        .WithMany("ContactAttempts")
                        .HasForeignKey("CareEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareWork.FollowUp", b =>
                {
                    b.HasOne("CommunityElderCare.Core.CareEvents.CareEvent", null)
                        .WithMany()
                        .HasForeignKey("CareEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareWork.ServiceOrder", b =>
                {
                    b.HasOne("CommunityElderCare.Core.CareEvents.CareEvent", null)
                        .WithMany()
                        .HasForeignKey("CareEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareWork.VisitTask", b =>
                {
                    b.HasOne("CommunityElderCare.Core.CareEvents.CareEvent", null)
                        .WithMany()
                        .HasForeignKey("CareEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.EmergencyContact", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.HealthRisk", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("HealthRisks")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ServiceNeed", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("ServiceNeeds")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrantField", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Identity.ConsentGrant", null)
                        .WithMany("Fields")
                        .HasForeignKey("ConsentGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.CareEvents.CareEvent", b =>
                {
                    b.Navigation("ContactAttempts");

                    b.Navigation("Evidence");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ElderProfile", b =>
                {
                    b.Navigation("EmergencyContacts");

                    b.Navigation("HealthRisks");

                    b.Navigation("ServiceNeeds");
                });

            modelBuilder.Entity("CommunityElderCare.Core.Identity.ConsentGrant", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
