// <auto-generated />
using System;
using CommunityElderCare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityElderCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunityCareDbContext))]
    partial class CommunityCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ElderProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttentionLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoDisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("NextCheckInDueAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AttentionLevel");

                    b.ToTable("ElderProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ElderProfiles_IsDemoData", "\"IsDemoData\" = 1");
                        });
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DemoName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "ContactOrder")
                        .IsUnique();

                    b.ToTable("EmergencyContacts", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.HealthRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "Code")
                        .IsUnique();

                    b.ToTable("HealthRisks", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ServiceNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElderProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElderProfileId", "Code")
                        .IsUnique();

                    b.ToTable("ServiceNeeds", (string)null);
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.EmergencyContact", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.HealthRisk", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("HealthRisks")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ServiceNeed", b =>
                {
                    b.HasOne("CommunityElderCare.Core.Elders.ElderProfile", null)
                        .WithMany("ServiceNeeds")
                        .HasForeignKey("ElderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityElderCare.Core.Elders.ElderProfile", b =>
                {
                    b.Navigation("EmergencyContacts");

                    b.Navigation("HealthRisks");

                    b.Navigation("ServiceNeeds");
                });
#pragma warning restore 612, 618
        }
    }
}
